Projects/devProfile/devProfile/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projetos.urls', namespace='projects')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projects/devProfile/projetos/urls.py
#url - view - template


from django.urls import path, include
from .views import Homepage, Projects, Detailprojects

app_name = 'projects'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('projetos/', Projects.as_view(), name='projects'),
    path('projetos/<int:pk>', Detailprojects.as_view(), name='detailprojects'),
]

Projects/devProfile/projetos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

LISTA_CATEGORIAS = (
    #(armazenar_bd, aparecer_para_usuario)
    ("ANALYSIS", "Data Analysis"),
    ("SCIENCE", "Data Science"),
    ("AUTOMATIONS", "Web Scraping RPA"),
    ("CERTIFICADOS", "Certificados"),
    ("OUTROS", "Outros"),
)

class Profile(models.Model):
    titulo = models.CharField(max_length=300)
    thumb = models.ImageField(upload_to='thumb_projetos')
    descricao = models.TextField()
    categoria = models.CharField(max_length=20, choices=LISTA_CATEGORIAS)
    visualizações = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo
    
# create your projects

class Project(models.Model):
    projetos = models.ForeignKey("Profile", related_name="projetos", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=300)
    link = models.URLField()

    def __str__(self):
        return self.projetos.titulo + " - " + self.titulo

Projects/devProfile/projetos/views.py
from typing import Any, Dict
from django.shortcuts import render
from .models import Profile
from django.views.generic import TemplateView, ListView, DetailView

# Create your views here.
class Homepage(TemplateView):
    template_name = "homepage.html"

class Projects(ListView):
    template_name = "projects.html"
    model = Profile

class Detailprojects(DetailView):
    template_name = "detailprojects.html"
    model = Profile

    def get_context_data(self, **kwargs):
        context = super(Detailprojects, self).get_context_data(**kwargs)
        other_projects = Profile.objects.filter(categoria=self.get_object().categoria)
        context["other_projects"] = other_projects
        return context

Projects/devProfile/projetos/templates/detailprojects.html
{% extends 'base.html' %}

{% block titulo %}
Detalhes - Projetos
{% endblock %}

{% block content %}
<div class ="py-10">
    <h1>{{ object.titulo }}</h1>
    <hr>
    <p>{{ object }}</p>
    <p>{{ object.descricao }}</p>
    
    <img src="{{ object.thumb.url }}">

    <h2>Projetos</h2>
    {% for projetos in object.projetos.all %}
    <a href="{{ projetos.link }}">
        <p>Projeto {{ forloop.counter }}: {{ projetos }}</p>
    </a>
    {% endfor %} 
</div>

<div class ="py-10">
    {% for projetos in other_projects %}
    <p>
        <a href="{% url 'projects:detailprojects' projetos.pk %}">
            {{ projetos.titulo }} 
        </a>
    </p>
    {% endfor %}
</div>
{% endblock %}

Projects/devProfile/projetos/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Home - Profile
{% endblock titulo %}

{% block content %}
<div class="min-h-screen bg-black bg-cover bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat">
    <div class="animation-container">
        <img src="{% static 'img/fundo.jpg' %}" class="animation" alt="">
    </div>

    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Sejam bem-vindos ao meu ambiente Python! Aqui, você encontrará uma variedade de projetos nos quais utilizei diversas tecnologias para diferentes segmentos. Tudo reunido em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Pesquise e utilize os projetos como base como quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar e/ou entrar em contato.
        </h4>
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    <div class="flex flex-grow items-stretch" style="justify-content: center; color: #000; gap: 5px;">
                        <input/>
                    <button class="bg-blue-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                        <span>
                            Acessar
                        </span>
                        <ion-icon name="chevron-forward-circle-outline"></ion-icon>
                    </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Python Language.
        </h2>
        <h5 class="md:text-xl text-lg">
            Todos os projetos foram feitos em python, utilizando suas bibliotecas e frameworks.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/py_pic.png' %}" class="w-5/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'img/py_dj.png' %}" class="w-5/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Django Framework.
        </h2>
        <h5 class="md:text-xl text-lg">
            Este portifólio foi feito em Django como forma de aprimoramento, mas também para networking e compartilhar meus conhecimentos.
        </h5>
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Compartilhe!
        </h2>
        <h5 class="md:text-xl text-lg">
            Dessa forma você compatilha conhecimentos e quem sabe me ajude a alcançar minha primeira vaga Dev.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/share_pic.png' %}" class="w-5/12" alt="">
    </div>
</section>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Portfólio</li>
        <li>dev_ivan_campaneli</li>
    </ul>
</footer>
{% endblock %}

Projects/devProfile/projetos/templates/projects.html
{% extends 'base.html' %}

{% block titulo %}
Projetos
{% endblock %}

{% block content %}
<div class ="py-10" >
    <h1>Lista de Projetos</h1>
    {% for projects in object_list %}
    <hr>
    <a href="{% url 'projects:detailprojects' projects.pk %}"><p>{{ projects.titulo }}</p></a>
    <p>{{ projects.descricao }}</p>
    <img src="{{ projects.thumb.url }}">
    {% endfor %}
</div>
{% endblock %}

Projects/devProfile/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block titulo %}
        {% endblock %}      	
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}
    {% endblock %} 
</head>
<body class="h-14 bg-gradient-to-r from-sky-500 to-indigo-500 text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}   
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>     
</body>
</html>

Projects/devProfile/templates/navbar.html
{% load static %}
<header>
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-3/12">
        <a href="/">
            <img class="w-4/12" src="{% static 'img/logo.png' %}" alt="My logo">
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        <div class="mr-2">
            <form>
                <input type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar...">
            </form>
        </div>
        <div class="mr-2">
            <a href="#">
                <button class="bg-blue-700 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>            
        </div>
        <div class="mr-2">
            <a href="#">
                <button class="bg-blue-700 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>             
        </div>    
    </div>
</nav>
</header>